services:
  go-app:
    container_name: login_register
    image: shardnguyen/login_register:1.0.0
    build: .
    environment:
      DB_HOST: go_db
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_NAME: postgres
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      - redis
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/var/lib/redis/data
volumes:
  pgdata:
  cache: